spring:
  datasource:
    password: superroot
    url: jdbc:mysql://localhost:3306/motion_sensor
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
sensor:
  create:
    exchange: sensor-create-exchange
    queue: sensor-create-queue
  delete:
    exchange: sensor-delete-exchange
    queue: sensor-delete-queue
room:
  attach-light:
    exchange: room-attach-light-exchange
    queue: room-attach-light-queue
  remove-light:
    exchange: room-remove-light-exchange
    queue: room-remove-light-queue
server:
  port: 8083